-- Create the community_posts table
CREATE TABLE IF NOT EXISTS public.community_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid, -- Intentionally NOT referencing auth.users so fake data works 
    author_name text NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    likes integer DEFAULT 0
);

-- Enable Row Level Security (RLS) but allow everyone to read and insert for the sake of the feed working
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read posts
CREATE POLICY "Anyone can read community posts"
ON public.community_posts FOR SELECT
TO public
USING (true);

-- Allow authenticated users to insert posts
CREATE POLICY "Users can insert community posts"
ON public.community_posts FOR INSERT
TO authenticated
WITH CHECK (true);

-- Allow authenticated users to update likes
CREATE POLICY "Users can update likes"
ON public.community_posts FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);


-- Insert seed data directly
INSERT INTO public.community_posts (user_id, author_name, content, created_at, likes) VALUES
('00000000-0000-0000-0000-000000000001', 'Priya Mehta', 'Just hit a new PR on squats today! 100kg for 3 reps! 🎉 So excited to finally cross that milestone.', NOW() - INTERVAL '2 hours', 24),
('00000000-0000-0000-0000-000000000002', 'Rahul Sharma', 'Rest day feels weird when you''re used to pushing hard 6 days a week... but the recovery is just as important as the iron.', NOW() - INTERVAL '1 day', 15),
('00000000-0000-0000-0000-000000000003', 'Sneha Kapoor', 'Does anyone else feel like Bulgarian split squats are a form of medieval torture? 🥵 Leg day is done though!', NOW() - INTERVAL '3 hours', 42),
('00000000-0000-0000-0000-000000000004', 'Arjun Singh', 'The new AR Pushup Analyzer is actually crazy accurate. It called out my hip sag immediately on rep 12.', NOW() - INTERVAL '5 hours', 18),
('00000000-0000-0000-0000-000000000005', 'Vikram Nair', 'Meal prep Sunday! Got 15 meals lined up for the week to hit that 180g protein goal without thinking about it.', NOW() - INTERVAL '2 days', 31);
